# fly.toml app configuration file generated for barman-bot-sergei-misty-field-6598 on 2024-04-22T20:51:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'barman-bot-sergei-misty-field-6598'
primary_region = 'cdg'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
PRIMARY_REGION = 'cdg'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
