# fly.toml app configuration file generated for barman-bot-sergei on 2023-05-10T19:07:32+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "barman-bot-sergei"
primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PRIMARY_REGION = "cdg"
